using System;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.RenderGraphModule;
using UnityEngine.Rendering.Universal;
using UnityEngine.Serialization;

public class OutlineRendererFeature : ScriptableRendererFeature
{
    [SerializeField] private OutlineSettings m_Settings = new();
    private OutlinePass _pass;

    public override void Create()
    {
        _pass = new OutlinePass(m_Settings);
        _pass.renderPassEvent = RenderPassEvent.AfterRenderingTransparents;
    }

    public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
    {
        renderer.EnqueuePass(_pass);
    }

    [Serializable]
    public class OutlineSettings
    {
        [Header("Source")] public string MaskTextureName = "_OutlineMask";
        [Header("Outline")] [Range(1, 10)] public int Width = 2;
        public Color Color = Color.yellow;
        [Range(0, 5)] public float Intensity = 1f;

        [FormerlySerializedAs("CompositeMaterial")]
        public Material OutlineMaterial;
    }

    private class OutlinePass : ScriptableRenderPass
    {
        private readonly OutlineSettings _settings;

        private class PassData
        {
            public OutlineSettings Settings;
            public Vector2 PixelSize;
        }

        public OutlinePass(OutlineSettings settings)
        {
            _settings = settings;
            renderPassEvent = RenderPassEvent.AfterRenderingTransparents;
        }

        public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
        {
            UniversalResourceData resourceData = frameData.Get<UniversalResourceData>();
            UniversalCameraData cameraData = frameData.Get<UniversalCameraData>();

            Vector2 pixelSize = new(1.0f / cameraData.cameraTargetDescriptor.width,
                1.0f / cameraData.cameraTargetDescriptor.height);
            int maskTextureID = Shader.PropertyToID(_settings.MaskTextureName);

            using IRasterRenderGraphBuilder builder = renderGraph.AddRasterRenderPass<PassData>("Outline Pass", out var passData);
            passData.Settings = _settings;
            passData.PixelSize = pixelSize;
            // Declare dependency on the texture generated by RenderTexturePass
            builder.UseGlobalTexture(maskTextureID, AccessFlags.Read);
            // Render back into the camera color buffer
            builder.SetRenderAttachment(resourceData.activeColorTexture, 0, AccessFlags.ReadWrite);

            builder.SetRenderFunc((PassData data, RasterGraphContext context) =>
            {
                Material material = data.Settings.OutlineMaterial;
                material.SetColor("_OutlineColor", data.Settings.Color);
                material.SetFloat("_OutlineWidth", data.Settings.Width);
                material.SetFloat("_OutlineIntensity", data.Settings.Intensity);
                material.SetVector("_PixelSize", data.PixelSize);
                Blitter.BlitTexture(context.cmd, new Vector4(1, 1, 0, 0), material, 0);
            });
        }
    }
}